apiVersion: v1
kind: ConfigMap
metadata:
  namespace: elk-test
  name: kibana-test
  labels:
    app: kibana-test
data:
  kibana.yml: |-
    server.host: 0.0.0.0
    elasticsearch:
      hosts: ${ELASTICSEARCH_URL}
      username: ${ELASTICSEARCH_USER}
      password: ${ELASTICSEARCH_PASSWORD}