apiVersion: v1
kind: Secret
metadata:
  name: registry-creds-ecr
  namespace: kube-system
  labels:
    app: registry-creds
    kubernetes.io/minikube-addons: registry-creds
    cloud: ecr
data:
  AWS_ACCESS_KEY_ID: QUtJQTJTS0dQS1lJU0RQS01aTk0=
  AWS_SECRET_ACCESS_KEY: SDl5QzZxaStLbWcxWEQzeWZUekhjWUxDbk94MHJGN1VVR0ZOWG5tZA==
  aws-account: NzI2NTM0MTQ5NjQ5
  aws-region: dXMtZWFzdC0x
  aws-assume-role: ""
  AWS_SESSION_TOKEN: "Y2hhbmdlbWU="
type: Opaque