apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-test
  namespace: elk-test
  labels:
    app: kibana-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana-test
  template:
    metadata:
      labels:
        app: kibana-test
    spec:
      containers:
      - name: kibana-test
        image: docker.elastic.co/kibana/kibana:7.16.2
        env:
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch-7-master-test:9200"
        - name: ELASTICSEARCH_USER
          value: "elastic"
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-pw-elastic
              key: password
        resources:
          limits:
            cpu: 550m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 500Mi
        ports:
        - containerPort: 5601
          name: kibana
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /usr/share/kibana/config/kibana.yml
          readOnly: true
          subPath: kibana.yml
      volumes:
      - name: config
        configMap:
          name: kibana-test