apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello2
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1200"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1200"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1200"
    nginx.ingress.kubernetes.io/proxy-body-size: "10240m"
spec:
  rules:
  - host: hello2.fluig.io
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
        path: /