kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello2
  namespace: poc-test
  labels:
    app: hello2
spec:
  selector:
    matchLabels:
      app: hello2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  template:
    metadata:
      labels:
         app: hello2
    spec:
      imagePullSecrets:
        - name: awsecr-cred
      containers:
        - name: hello
          image: 726534149649.dkr.ecr.us-east-1.amazonaws.com/hello:v2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: hello2
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 2 
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
