apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-pv
  labels:
    type: local
spec:
  storageClassName: generic
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/var/lib/mongo"
    server: 172.31.74.229
    readOnly: false
