apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana-events
  namespace: elk-test
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: http
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1200"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1200"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1200"
    nginx.ingress.kubernetes.io/proxy-body-size: "10240m"
    
spec:
  rules:
  - host: kibana.cluster.k8s.domain.io
    http:
      paths:
      - backend:
          serviceName: kibana-events
          servicePort: 5601
        path: /
  - host: kibana.domain.net
    http:
      paths:
      - backend:
          serviceName: kibana-events
          servicePort: 5601
        path: /