---
kind: pipeline
type: docker
name: k8s-cluster

steps:
      
- name: initialize aws plugin for terraform
  image: unitynts/terraform:1.0
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret
  commands:
  - terraform init
  
- name: create aws infra
  image: unitynts/terraform:1.0
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret
  commands:
  - terraform apply -auto-approve
  
- name: apply ansible playbook
  image: unitynts/terraform:1.0
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret
    PRIVATE_KEY:
      from_secret: private_key
  commands:
  - mkdir -p ~/.ssh/
  - echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ln -s /usr/bin/python3 /usr/bin/python
  - chmod +x ec2.py
  - ssh-keygen -p -P slack3128 -N "" -f ~/.ssh/id_rsa
  - ansible-playbook -i ec2.py --limit "tag_name_k8s" -u ubuntu --ssh-common-args='-o StrictHostKeyChecking=no' --private-key ~/.ssh/id_rsa k8s-cluster.yml
