kind: Service
apiVersion: v1
metadata:
  name: hello2
  namespace: poc-test
  labels:
    app: hello2
spec:
  selector:
    app: hello2
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8080
