apiVersion: v1
kind: ConfigMap
metadata:
  namespace: elk-test
  name: elasticsearch-7-master-test
  labels:
    app: elasticsearch-7-master-test
    role: master
data:
  elasticsearch.yml: |
    xpack.security.enabled: true
    xpack.security.transport.ssl.enabled: true
    xpack.security.transport.ssl.verification_mode: full
    xpack.security.transport.ssl.keystore.path: /usr/share/elasticsearch/config/certs-gen/keystore.p12
    xpack.security.transport.ssl.truststore.path: /usr/share/elasticsearch/config/certs-gen/keystore.p12
    xpack.security.authc:
      anonymous:
        username: anonymous 
        roles: superuser
        authz_exception: true 