apiVersion: v1
kind: Service
metadata:
  name: kibana-events
  namespace: elk-test
  labels:
    app: kibana-events
    component: kibana
spec:
  selector:
    app: kibana-events
  ports:
  - name: http
    port: 5601
    protocol: TCP
